# Generated by Django 6.0.8 on 2026-08-05 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Places',
            name='built_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='Places',
            name='rooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='Places',
            name='price',
            field=models.FloatField(),
        ),
    ]
