# Generated by Django 6.1 on 2026-08-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_places_built_at_places_rooms_alter_places_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='floor',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='place',
            name='owner',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
