# Generated by Django 6.1 on 2026-08-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_places_built_at_places_rooms_alter_places_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
    ]
