# Generated by Django 6.1 on 2026-08-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_owner_remove_person_car_alter_place_owner_delete_car_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
