# Generated by Django 6.1 on 2026-08-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_rename_owner_place_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
