# Generated by Django 6.1 on 2026-08-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='phone',
            field=models.CharField(null=True),
        ),
    ]
